<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20260417145439 extends AbstractMigration
{
    public function getDescription(): string
    {
        return '';
    }

    public function up(Schema $schema): void
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->addSql('DROP SEQUENCE greeting_id_seq CASCADE');
        $this->addSql('CREATE TABLE actor (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, firstname VARCHAR(50) NOT NULL, lastname VARCHAR(50) NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE TABLE actor_content (actor_id INT NOT NULL, content_id INT NOT NULL, PRIMARY KEY (actor_id, content_id))');
        $this->addSql('CREATE INDEX IDX_DC3060C310DAF24A ON actor_content (actor_id)');
        $this->addSql('CREATE INDEX IDX_DC3060C384A0A3ED ON actor_content (content_id)');
        $this->addSql('CREATE TABLE content (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, title VARCHAR(100) NOT NULL, description VARCHAR(500) DEFAULT NULL, release_date DATE NOT NULL, entrances INT DEFAULT NULL, poster VARCHAR(255) DEFAULT NULL, minimal_age INT NOT NULL, type VARCHAR(30) DEFAULT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE TABLE interaction (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, is_liked BOOLEAN NOT NULL, rate DOUBLE PRECISION DEFAULT NULL, comment VARCHAR(1000) DEFAULT NULL, date DATE NOT NULL, associated_user_id INT NOT NULL, associated_content_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_378DFDA7BC272CD1 ON interaction (associated_user_id)');
        $this->addSql('CREATE INDEX IDX_378DFDA76F1782AC ON interaction (associated_content_id)');
        $this->addSql('CREATE TABLE "user" (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, email VARCHAR(180) NOT NULL, roles JSON NOT NULL, password VARCHAR(255) NOT NULL, firstname VARCHAR(50) NOT NULL, lastname VARCHAR(50) NOT NULL, date_of_birth DATE NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_IDENTIFIER_EMAIL ON "user" (email)');
        $this->addSql('CREATE TABLE user_friends (user_source INT NOT NULL, user_target INT NOT NULL, PRIMARY KEY (user_source, user_target))');
        $this->addSql('CREATE INDEX IDX_79E36E633AD8644E ON user_friends (user_source)');
        $this->addSql('CREATE INDEX IDX_79E36E63233D34C1 ON user_friends (user_target)');
        $this->addSql('ALTER TABLE actor_content ADD CONSTRAINT FK_DC3060C310DAF24A FOREIGN KEY (actor_id) REFERENCES actor (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE actor_content ADD CONSTRAINT FK_DC3060C384A0A3ED FOREIGN KEY (content_id) REFERENCES content (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE interaction ADD CONSTRAINT FK_378DFDA7BC272CD1 FOREIGN KEY (associated_user_id) REFERENCES "user" (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE interaction ADD CONSTRAINT FK_378DFDA76F1782AC FOREIGN KEY (associated_content_id) REFERENCES content (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE user_friends ADD CONSTRAINT FK_79E36E633AD8644E FOREIGN KEY (user_source) REFERENCES "user" (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE user_friends ADD CONSTRAINT FK_79E36E63233D34C1 FOREIGN KEY (user_target) REFERENCES "user" (id) ON DELETE CASCADE');
        $this->addSql('DROP TABLE greeting');
    }

    public function down(Schema $schema): void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->addSql('CREATE SEQUENCE greeting_id_seq INCREMENT BY 1 MINVALUE 1 START 1');
        $this->addSql('CREATE TABLE greeting (id INT NOT NULL, name VARCHAR(255) NOT NULL, PRIMARY KEY (id))');
        $this->addSql('ALTER TABLE actor_content DROP CONSTRAINT FK_DC3060C310DAF24A');
        $this->addSql('ALTER TABLE actor_content DROP CONSTRAINT FK_DC3060C384A0A3ED');
        $this->addSql('ALTER TABLE interaction DROP CONSTRAINT FK_378DFDA7BC272CD1');
        $this->addSql('ALTER TABLE interaction DROP CONSTRAINT FK_378DFDA76F1782AC');
        $this->addSql('ALTER TABLE user_friends DROP CONSTRAINT FK_79E36E633AD8644E');
        $this->addSql('ALTER TABLE user_friends DROP CONSTRAINT FK_79E36E63233D34C1');
        $this->addSql('DROP TABLE actor');
        $this->addSql('DROP TABLE actor_content');
        $this->addSql('DROP TABLE content');
        $this->addSql('DROP TABLE interaction');
        $this->addSql('DROP TABLE "user"');
        $this->addSql('DROP TABLE user_friends');
    }
}
